### ISSUE TITLE
Need executable 'ar' to convert dir to deb

### ISSUE THREAD

**Issue by sanchoooo** [skandyla/docker-fpm#1]
Attempting to create a deb file from a directory resulted in the error:

docker run --rm -w /data -v /workdir:/data skandyla/fpm -a all -f -C control-plane -s dir -t deb --rpm-os linux --name plane-images --version=1.0--prefix="/" -p DEBS/plane-images.deb;

{:timestamp=>"2019-02-14T22:45:38.644053+0000", :message=>"Need executable 'ar' to convert dir to deb", :level=>:error}

To resolve the issue, I added `binutils` to the `apt-get install -y`

**Comment by skandyla** [comment]
Sorry, missed this issue.
@bdeknijf Thanks for the contribution.
